#!/usr/bin/env ruby

require 'rubygems'
require 'optparse'
require 'nokogiri'
require 'open-uri'
require 'csv'
require 'json'

options = {}
OptionParser.new do |opts|
  opts.banner = 'Converts Shopify order feed xml to PowerReviews order feed csv'

  opts.on('-h', '--host URL', 'Shopify order feed url') { |host| options[:host] = host }
  opts.on('-u', '--username USERNAME', 'Admin username') { |username| options[:username] = username }
  opts.on('-p', '--password PASSWORD', 'Admin password') { |password| options[:password] = password }
end.parse!

raise 'host parameter must be provided' if options[:host].nil?

xml = Nokogiri::XML(open(options[:host], http_basic_authentication: [options[:username], options[:password]]))
page_id_map = File.exists?('page-id-map.json') ? JSON.parse(File.read('page-id-map.json')) : {}

csv = CSV.generate do |csv|
  csv << ['order_id', 'page_id', 'first_name', 'last_name', 'email', 'order_date', 'variant', 'user_id']

  xml.xpath('//item').each do |order_item|
    order_item.xpath('./*/shopify:line_item').each do |item|
      csv << [
        order_item.at('shopify|order_id').text,
        page_id_map[item.at('shopify|sku').text] || '',
        order_item.at('shopify|billing_address').at('shopify|first_name').text,
        order_item.at('shopify|billing_address').at('shopify|last_name').text,
        order_item.at('shopify|email').text,
        order_item.at('shopify|created_at').text,
        '',
        ''
      ]
    end
  end
end

puts csv
